all:
  hosts:
    web_server:
        ansible_host: 54.75.132.197
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /Users/sathurjan/BST/Keys/jenkins-codecommit.pem


# [web_server]
# 63.32.117.241 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/sathurjan/BST/Keys/jenkins-codecommit.pem


# [defaults]
# inventory = hosts
# remote_user = ubuntu
# private_key_file = /Users/sathurjan/BST/Keys/jenkins-codecommit.pem
# host_key_checking = False
